resolver: lts-8.21
packages:
- .
- location: /home/syd/cs-syd/code/open-source/easyspec/easyspec
- location: /home/syd/cs-syd/code/open-source/easyspec/easyspec-evaluate
- location:
    git: git@github.com:NorfairKing/quickspec.git
    commit: 58d2c4ef66da806f938281159dc66bf2a9d062a1
  extra-dep: true
  # - location:
  #       git: git@github.com:NorfairKing/easyspec.git
  #       commit: 37eb4bdf1fe61e7a6b93fa94ed14dde5591931e3
  #   subdirs:
  #     - easyspec
  #     - easyspec-evaluate
  #   extra-dep: true
extra-deps:
  # - quickspec-2
  # - easyspec-0.0.0.0
  # - easyspec-evaluate-0.0.0.0
- haspell-1.1.0
- lambdatex-0.2.0.0
- shake-path-0.0.0.0
- zifter-0.0.1.2
- validity-0.3.3.0
- validity-path-0.1.0.1
- directory-1.3.0.0
- jukebox-0.2.17
- twee-0.1
- minisat-0.1.2
- edit-distance-vector-1.0.0.4
