resolver: lts-8.21
packages:
- .
- location:
    git: git@github.com:NorfairKing/quickspec.git
    commit: 58d2c4ef66da806f938281159dc66bf2a9d062a1
  extra-dep: true
- location:
    git: git@github.com:NorfairKing/easyspec.git
    commit: 192c52ebfe56b634c140c5e9c81d6dfaa48d37ca
  subdirs:
    - easyspec
    - easyspec-evaluate
  extra-dep: true
extra-deps:
- haspell-1.1.0
- lambdatex-0.2.0.0
- shake-path-0.0.0.0
- zifter-0.0.1.2
- validity-0.3.3.0
- validity-path-0.1.0.1
- directory-1.3.0.0
- jukebox-0.2.17
- twee-0.1
- minisat-0.1.2
- edit-distance-vector-1.0.0.4
- genvalidity-hspec-0.3.1.0
- genvalidity-path-0.1.0.2
- genvalidity-0.3.2.0
